[package]
name = "base_transaction"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
csv = "1.1.6"
serde = {version = "1.0.137", features = ["derive"]}

[dev-dependencies]
float-cmp = "0.9.0"
